variables:
  CACHE_VERSION: 20200520

jobs:
  - job: setup
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: none
      - bash: |
          python3 -V
          mkdir dials-shallow
          cd dials-shallow
          git init
          git remote add origin $(Build.Repository.Uri)
          git fetch --depth 1 --progress --no-recurse-submodules origin $(Build.SourceBranchName)
          git checkout FETCH_HEAD
          python3 -m compileall . -q | sed "s/^\*\*\* */##vso[task.logissue type=error]/"
        displayName: Syntax validation
        workingDirectory: $(Pipeline.Workspace)
      - bash: |
          echo "##vso[task.setvariable variable=CURRENT_WEEK;isOutput=true]$(date +W%W)"
          echo "##vso[task.setvariable variable=TODAY_ISO;isOutput=true]$(date +%Y%m%d)"
        displayName: Set up build constants
        name: constants

#  - template: ./.azure-pipelines/azure-pipelines-linux.yml
#  - template: ./.azure-pipelines/azure-pipelines-osx.yml
#  - template: ./.azure-pipelines/azure-pipelines-win.yml
