variables:
  CACHE_VERSION: 20200520

jobs:
  - job: setup
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        fetchDepth: 1
        submodules: false
        path: ./dials-shallow
        displayName: Checkout $(Build.SourceBranch)

      - bash: |
          python3 -V
          ls -la
          ls -la dials-shallow
        displayName: Syntax validation
        workingDirectory: $(Pipeline.Workspace)

      - bash: |
          echo "##vso[task.setvariable variable=CURRENT_WEEK;isOutput=true]$(date +W%W)"
          echo "##vso[task.setvariable variable=TODAY_ISO;isOutput=true]$(date +%Y%m%d)"
        displayName: Set up build constants
        name: constants

#  - template: ./.azure-pipelines/azure-pipelines-linux.yml
#  - template: ./.azure-pipelines/azure-pipelines-osx.yml
#  - template: ./.azure-pipelines/azure-pipelines-win.yml
