# Templates for linux, macOS, and Windows
# Based on approach from conda-forge

variables:
  CACHE_VERSION: 20200520

jobs:
  - template: ./.azure-pipelines/azure-pipelines-linux.yml
    parameters:
      distribution: centos
      version: 7
#  - template: ./.azure-pipelines/azure-pipelines-osx.yml
#    parameters:
#      vmImage: macOS-10.14
#      xcode_version: 10.2.1
#  - template: ./.azure-pipelines/azure-pipelines-win.yml
