jobs:
  - job: setup
    displayName: syntax validation
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: none

      - bash: |
          echo "not doing anything :)"
        displayName: Syntax validation
