#!/bin/bash

# Identify all python files added or modified in pull request
CHANGED_FILES=$(git diff --name-only --diff-filter=AM $TRAVIS_BRANCH...HEAD -- "*.py")

# This list is empty if we are not in a pull request, so bail out
[ -z "$CHANGED_FILES" ] && echo This is not a pull request or no relevant changes. Skipping test. && exit 0

pip install flake8
flake8 --select=E711,E712,E713,E714,E721,F401,F402,F403,F632,F811,F812,F821,F841,F901,W605 $CHANGED_FILES
