#!/bin/bash

echo Travis branch: $TRAVIS_BRANCH
echo TB:
git rev-parse $TRAVIS_BRANCH
echo HEAD:
git rev-parse HEAD

CHANGED_FILES=$(git diff --name-only --diff-filter=AM $TRAVIS_BRANCH...HEAD | grep "\.py$")
echo Testing changed files:
echo $CHANGED_FILES
