# Script for building CCTBX
# linux image descriptions
# https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md

jobs:
- job: linux_64
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 60
#  dependsOn: syntax
  strategy:
    maxParallel: 3
    matrix:
      python3.6:
        PYTHON_VERSION: 3.6
#     python3.7:
#       PYTHON_VERSION: 3.7
#     python3.8:
#       PYTHON_VERSION: 3.8
# container:
#   image: ${{ parameters.distribution }}:${{ parameters.version }}
#   options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
#
  steps:
# # https://github.com/ApexAI/performance_test/blob/master/azure-pipelines.yml#L9-L17
#
# # centos setup
# - script: |
#     /tmp/docker exec -t -u 0 ci-container \
#     sh -c "yum install -y sudo"
#   displayName: Set up sudo
#   condition: eq('${{ parameters.distribution }}', 'centos')
#
# - script: |
#     sudo yum groupinstall -y 'Development Tools'
#     sudo yum install -y python-argparse mesa-libGLU-devel mesa-libGL-devel
#   displayName: Install dependencies
#   condition: eq('${{ parameters.distribution }}', 'centos')
#
  # ubuntu setup
#  - script: |
 #     /tmp/docker exec -t -u 0 ci-container \
#      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
#    displayName: Set up sudo

  - script: |
      sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
    displayName: Install dependencies

  # build
#  - template: ./unix-build.yml
