parameters:
- name: 'CURRENT_WEEK'
  type: string
- name: 'TODAY_ISO'
  type: string

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  dependsOn: setup
#  strategy:
#    matrix:
#      python36:
#        PYTHON_VERSION: 3.6
#     python37:
#       PYTHON_VERSION: 3.7
#     python38:
#       PYTHON_VERSION: 3.8
  timeoutInMinutes: 90

  steps:
  - script: |
      echo Current week: ${{ parameters.CURRENT_WEEK }}
      echo Today: ${{ parameters.TODAY_ISO }}
    displayName: Show variables

#  - script: |
#      sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
#    displayName: Install dependencies
#
#  - template: ./unix-build.yml
