jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  dependsOn: setup
  variables:
    CURRENT_WEEK1: $[ dependencies.setup.outputs['constants.CURRENT_WEEK'] ]
    CURRENT_WEEK2: $[ dependencies.setup.outputs['CURRENT_WEEK'] ]

#  strategy:
#    matrix:
#      python36:
#        PYTHON_VERSION: 3.6
#     python37:
#       PYTHON_VERSION: 3.7
#     python38:
#       PYTHON_VERSION: 3.8
  timeoutInMinutes: 90

  steps:
  - script: |
      echo Current week: ${{ parameters.CURRENT_WEEK }}
      echo Today: ${{ parameters.TODAY_ISO }}
      echo Current week: ${{ parameters['CURRENT_WEEK'] }}
      echo Today: ${{ parameters['TODAY_ISO'] }}
      echo Current week: $(parameters.CURRENT_WEEK)
      echo Today: $(parameters.TODAY_ISO)
      echo Current week: $(CURRENT_WEEK)
      echo Today: $(TODAY_ISO)
      echo Current week: $(CURRENT_WEEK1)
      echo Current week: $(CURRENT_WEEK2)
      echo more 1: $[ dependencies.setup.outputs['constants.CURRENT_WEEK'] ]
      echo more 2: $[ dependencies.setup.outputs['CURRENT_WEEK'] ]
      echo Current week: $CURRENT_WEEK
      echo Today: $TODAY_ISO
    displayName: Show variables

#  - script: |
#      sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
#    displayName: Install dependencies
#
#  - template: ./unix-build.yml
