# Script for building CCTBX on linux and macOS
#
# Variables:
#   CACHE_VERSION: unique string
#   PYTHON_VERSION: string in the form of "3.x"

steps:

- script: |
    echo "##vso[task.setvariable variable=CURRENT_WEEK]W$(date +%W)"
  displayName: Set up cache expiration

- checkout: self
  path: ./dials-checkout
  displayName: Checkout $(Build.SourceBranch)

- task: Cache@2
  inputs:
    key: '"repositories" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | installer/bootstrap.py | "$(Build.SourceBranch)"'
    restoreKeys: |
      "repositories" | "$(CACHE_VERSION)-$(CURRENT_WEEK)" | installer/bootstrap.py | "refs/heads/master"
    path: $(Pipeline.Workspace)/modules
    cacheHitVar: REPOSITORIES_CACHED
  displayName: Restore repository cache

- script: |
    mkdir -p modules
    ln ../dials-checkout modules/dials -nsf
    python modules/dials/installer/bootstrap.py update
  displayName: Checkout repositories using bootstrap
  workingDirectory: $(Pipeline.Workspace)
  condition: ne(variables.REPOSITORIES_CACHED, 'true')

- script: |
    for repository in cctbx_project dxtbx; do
      if [ ! -e $(Pipeline.Workspace)/modules/${repository} ]; then
        echo Cloning ${repository} from scratch
        git clone https://github.com/cctbx/${repository}.git --depth=1 $(Pipeline.Workspace)/modules/${repository}
      fi

      echo Checking out latest ${repository} commit
      cd $(Pipeline.Workspace)/modules/${repository} || exit 1
      git fetch origin master --depth=1 || exit 2
      git checkout FETCH_HEAD || exit 3
      echo -n "${repository} is at commit "
      git show --oneline -s --no-abbrev-commit || exit 4
    done
  displayName: Update cctbx/dxtbx repository
  workingDirectory: $(Pipeline.Workspace)
  condition: eq(variables.REPOSITORIES_CACHED, 'true')

- script: |
    echo I am here:
    pwd
    echo This is what lives here:
    ls -la
    ls -la *
  displayName: Some basic scripting
  workingDirectory: $(Pipeline.Workspace)

- task: Cache@2
  inputs:
    key: '"base" | "$(CACHE_VERSION)" | "$(Agent.OS)" | "$(PYTHON_VERSION)" | .conda-envs/linux.txt'
    path: $(Pipeline.Workspace)/conda_base
    cacheHitVar: BASE_CACHED
  displayName: Restore cached base environment

- script: |
    python modules/dials/installer/bootstrap.py base --python $(PYTHON_VERSION)
  displayName: Create python $(PYTHON_VERSION) base environment
  workingDirectory: $(Pipeline.Workspace)
  condition: ne(variables.BASE_CACHED, 'true')

- script: |
    echo I am here:
    pwd
    echo This is what lives here:
    ls -la
    ls -la *
  displayName: Some basic scripting
  workingDirectory: $(Pipeline.Workspace)

- task: Cache@2
  inputs:
    key: '"build" | "$(CACHE_VERSION)" | "$(Agent.OS)" | "$(PYTHON_VERSION)" | installer/bootstrap.py | .conda-envs/linux.txt'
    path: $(Pipeline.Workspace)/build
    cacheHitVar: BUILD_CACHED
  displayName: Restore cached build

- script: |
    python modules/dials/installer/bootstrap.py build
  displayName: Run initial DIALS build
  workingDirectory: $(Pipeline.Workspace)
  condition: ne(variables.BUILD_CACHED, 'true')

- script: |
    . setpaths.sh
    make reconf
  displayName: Run incremental DIALS build
  workingDirectory: $(Pipeline.Workspace)/build
  condition: eq(variables.BUILD_CACHED, 'true')

- script: |
    echo I am here:
    pwd
    echo This is what lives here:
    ls -la
    ls -la *
  displayName: Some basic scripting
  workingDirectory: $(Pipeline.Workspace)

- script: |
    . build/setpaths.sh
    cd modules/dials
    libtbx.pytest -ra -n auto -v
  displayName: Run tests
  workingDirectory: $(Pipeline.Workspace)

- script: |
    echo I am here:
    pwd
    echo This is what lives here:
    ls -la
    ls -la *
  displayName: Some basic scripting
  workingDirectory: $(Pipeline.Workspace)

- script: |
    echo Preparing cache
    for repository in modules/*; do
      if [ -e ${repository}/.git ]; then
        echo Cleaning directory ${repository}
        cd ${repository}
        git reset --hard HEAD
        git clean -dffxq
        cd -
      fi
    done
    ls -la modules
  displayName: Preparing cache
  workingDirectory: $(Pipeline.Workspace)
