# Script for building CCTBX on linux and macOS
#
# Variables:
#   CACHE_VERSION: unique cache identifier
#   CURRENT_WEEK: weekly changing cache identifier
#   TODAY_ISO: today's date in ISO format, eg. "20200531"
#   PYTHON_VERSION: string in the form of "3.x"

steps:

- checkout: self
  path: ./dials-checkout
  displayName: Checkout $(Build.SourceBranch)

- script: |
    echo Current week: $(CURRENT_WEEK)
    echo Today: $(TODAY_ISO)
    echo Cache version: $(CACHE_VERSION)
    echo Python version: $(PYTHON_VERSION)
  displayName: Show variables

