# Script for building CCTBX on linux and macOS
#
# Variables:
#   PYTHON_VERSION: py27, py36
#   OS: linux-64, osx-64

steps:

- checkout: self
  path: ./modules/dials

- task: Cache@2
  inputs:
    key: 'repositories | $(CACHE_VERSION) | master'
    path: $(Pipeline.Workspace)/modules
  displayName: Restore repository cache $(CACHE_VERSION)

- script: |
    echo I am here:
    pwd
    echo This is what lives here:
    ls -la
    ls -la *
  displayName: Some basic scripting
  workingDirectory: $(Pipeline.Workspace)

- script: |
    python modules/dials/installer/bootstrap.py update
  displayName: Update sources
  workingDirectory: $(Pipeline.Workspace)

- script: |
    echo I am here:
    pwd
    echo This is what lives here:
    ls -la
    ls -la *
  displayName: Some basic scripting
  workingDirectory: $(Pipeline.Workspace)

- script: |
    echo Installing with python version $(PYTHON_VERSION)
    python modules/dials/installer/bootstrap.py base --python $(PYTHON_VERSION)
  displayName: Installing python $(PYTHON_VERSION) base environment
  workingDirectory: $(Pipeline.Workspace)

- script: |
    echo I am here:
    pwd
    echo This is what lives here:
    ls -la
    ls -la *
  displayName: Some basic scripting
  workingDirectory: $(Pipeline.Workspace)

#- script: |
#    python modules/dials/installer/bootstrap.py build
#  displayName: Build
#  workingDirectory: $(Pipeline.Workspace)

- script: |
    echo I am here:
    pwd
    echo This is what lives here:
    ls -la
    ls -la *
  displayName: Some basic scripting
  workingDirectory: $(Pipeline.Workspace)

#- script: |
#    python modules/dials/installer/bootstrap.py tests
#  displayName: Run tests
#  workingDirectory: $(Pipeline.Workspace)

- script: |
    echo I am here:
    pwd
    echo This is what lives here:
    ls -la
    ls -la *
  displayName: Some basic scripting
  workingDirectory: $(Pipeline.Workspace)

- script: |
    echo Preparing cache
    rm -rf modules/dials
    for repository in modules/*; do
      if [ -e ${repository}/.git ]; then
        echo Cleaning directory ${repository}
        cd ${repository}
        git reset --hard HEAD
        git clean -dffxq
        cd -
      fi
    done
    ls -la modules
  displayName: Preparing cache
  workingDirectory: $(Pipeline.Workspace)
  
