# Variables:
#   CACHE_VERSION: unique cache identifier
#   CURRENT_WEEK: weekly changing cache identifier
#   PYTHON_VERSION: string in the form of "3.x"
#   TODAY_ISO: today's date in ISO format, eg. "20200531"

steps:

- checkout: none

# If other source repositories are not cached then download
# them using the bootstrap script
- bash: |
    pwd
    echo -----
    ls -la
    echo -----
    ls -la /Users
    echo -----
    ls -la /Users/runner
    echo -----
    ls -la /Users/runner/runners
    echo -----
    mkdir /Users/runner/runners/test
    ls -la /Users/runner/runners
    echo -----
  displayName: runner experiments
  workingDirectory: $(Pipeline.Workspace)
