# Script for building CCTBX on linux and macOS
#
# Variables:
#   PYTHON_VERSION: py27, py36
#   OS: linux-64, osx-64

steps:

- checkout: self
  path: ./modules/dials

- script: |
    echo I am here:
    pwd
    echo This is what lives here:
    ls -la
  displayName: Some basic scripting
  workingDirectory: $(Pipeline.Workspace)

- script: |
    python modules/dials/bootstrap.py update
  displayName: Update sources
  workingDirectory: $(Pipeline.Workspace)

- script: |
    python modules/dials/bootstrap.py base
  displayName: Installing base environment

- script: |
    python modules/dials/bootstrap.py build
  displayName: Build

- script: |
    python modules/dials/bootstrap.py test
  displayName: Run tests

