# This workflow will run static type checking on all source files
# and check pull requests for newly introduced type errors.

name: type checking (pull)
on: [ pull_request ]

jobs:
  pytype:
    runs-on: ubuntu-latest
    name: pytype

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        # This checks out the merged pull request by default,
        # we also need the parent commit to check for changes
        fetch-depth: 2
        path: dials

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        pip install pytype

    - name: Copy analysis script from merged branch
      run: |
        cp dials/.github/pytype/pytype-analysis.py .

    - name: Run type checking on pull request
      run: |
        pytype -j auto -n -k dials | tee pytypelog-merged

    - name: Check out pull request base
      run: |
        cd dials
        git checkout HEAD^1
        git clean -dffx
        git log -1 HEAD

    - name: Run type checking on pull request base
      run: |
        pytype -j auto -n -k dials | tee pytypelog-base

    - name: Parse pytype output
      run: |
        python pytype-analysis.py pytypelog-merged --base pytypelog-base --github --annotations annotation-output.txt

    - name: Add annotations
      uses: pytorch/add-annotations-github-action@master
      with:
        check_name: 'pytype'
        linter_output_path: 'annotation-output.txt'
        commit_sha: ${{ github.event.pull_request.head.sha }}
        regex: '^(?<filename>.*?):(?<lineNumber>\d+):(?<columnNumber>\d+): (?<errorCode>\w\d+) (?<errorDesc>.*)'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ failure() }}
